### ISSUE TITLE
Update to .NET Core

### ISSUE THREAD

**Issue by Youssef1313** [matthewrenze/clean-architecture-demo#11]

**Comment by matthewrenze** [comment]
Youssef,

Thanks for the suggestion to update this demo to .NET Core.

I'm eventually planning to update my Clean Architecture course (that uses this demo) to get things up-to-date. When I do, I plan to update this demo project using .NET Core.

I'm not sure when this will happen but I definitely have it on my radar once I finish updating my older data science courses.

Thanks!

Matthew

**Comment by matthewrenze** [comment]
Here's the update to .NET Core I created a few years ago: https://github.com/matthewrenze/clean-architecture-core
