### ISSUE TITLE
Discussion threads for topics 

### ISSUE THREAD

**Issue by pvanroos** [matthewrenze/clean-architecture-demo#2]
Hi Matthew,

I watched your PS course.  I liked it very much.  Where can I engage you in a thoughtful discussion on the topics introduced in your course?

Thanks,

Paul

**Comment by matthewrenze** [comment]
Paul,

Thanks for the feedback on my course. I really appreciate it!

If you'd like to discuss the course further, please feel free to email me
at info@matthewrenze.com and we'll schedule a time to chat.

Take care,

Matthew

**Comment by phlaz** [comment]
Hi Matthew

I've cloned your repo but I cant get it to compile as is. The NuGet restore runs and reports everything restored but the Service project wont build, with a bunch of missing reference errors. All project references seem to be intact with no exclamations but its not happy about something. All other projects build ok. I'm running VS 2017 15.6.2. Any advice?

Thanks

Philip

**Comment by matthewrenze** [comment]
Phillip,

I pulled down a fresh copy of the repo and built it using Visual Studio
Enterprise 15.5.6.

Everything (including the Service project) seemed to build and run just
fine.

I'm not sure what would be causing the errors you're encountering.

I would recommend taking a screenshot of the project references in the
Service project, then delete and re-add each of them to see if that fixes
the issue. In the event something got referenced with a hard-coded file
path, that should fix the broken reference.

Best of luck!

Matthew
