### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by edgarvalcarcel** [matthewrenze/clean-architecture-demo#4]
Hi Mathew. I have a Issue, what is best way to do a Security Implementation(user, login, Authorization, etc) in this Architecture? I had tried to implement OWIN inside, but is Hard, because on all, requires access to Database context from presentation layer, and others issues. How do you recomended implements a security middleware or other?

**Comment by matthewrenze** [comment]
[Note: A duplicate of this question was answered in Pluralsight's discussion forum.]
