### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by emeria-zz** [matthewrenze/clean-architecture-demo#8]
I am trying to run this solution, but getting database errors.  Should I have SQL Express or LocalDb installed?  Do I need to create the database prior to running, or should it be created on build/run?

![Imgur](https://i.imgur.com/OmLfVsS.png)

**Comment by matthewrenze** [comment]
Yes, you need to have SQL Express installed in order for Entity Framework to automatically create a database for the sample application.

**Comment by emeria-zz** [comment]
Thanks!  My issue was that I created a named instance, so I had to change:
`Data Source=(local);`
To
`Data Source=(local)\SQLEXPRESS;`
